# Dependabot configuration for automated dependency updates
# Documentation: https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Cargo (Rust) dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Stockholm"
    # Limit the number of open pull requests for Cargo dependencies
    open-pull-requests-limit: 5
    # Add labels to pull requests
    labels:
      - "dependencies"
      - "rust"
    # Group minor and patch updates together to reduce noise
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Customize commit messages
    commit-message:
      prefix: "cargo"
      prefix-development: "cargo-dev"
      include: "scope"
    # Ignore specific dependencies if needed (uncomment and modify as necessary)
    # ignore:
    #   - dependency-name: "clap"
    #     versions: ["5.x"]

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Stockholm"
    open-pull-requests-limit: 2
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"